# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings  # noqa: F401

import grpc

import grpc_generated.order_pb2 as order__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in order_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SubmitOrderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitSingleOrder = channel.unary_unary(
            '/SubmitOrderService/SubmitSingleOrder',
            request_serializer=order__pb2.SubmitSingleOrderRequest.SerializeToString,
            response_deserializer=order__pb2.SubmitSingleOrderResponse.FromString,
            _registered_method=True,
        )
        self.SubmitBookTrade = channel.unary_unary(
            '/SubmitOrderService/SubmitBookTrade',
            request_serializer=order__pb2.SubmitBookTradeRequest.SerializeToString,
            response_deserializer=order__pb2.SubmitBookTradeResponse.FromString,
            _registered_method=True,
        )
        self.SubmitPairOrder = channel.unary_unary(
            '/SubmitOrderService/SubmitPairOrder',
            request_serializer=order__pb2.SubmitPairOrderRequest.SerializeToString,
            response_deserializer=order__pb2.SubmitPairOrderResponse.FromString,
            _registered_method=True,
        )
        self.ChangePairOrder = channel.unary_unary(
            '/SubmitOrderService/ChangePairOrder',
            request_serializer=order__pb2.ChangePairOrderRequest.SerializeToString,
            response_deserializer=order__pb2.ChangePairOrderResponse.FromString,
            _registered_method=True,
        )
        self.CancelPairOrder = channel.unary_unary(
            '/SubmitOrderService/CancelPairOrder',
            request_serializer=order__pb2.CancelPairOrderRequest.SerializeToString,
            response_deserializer=order__pb2.CancelPairOrderResponse.FromString,
            _registered_method=True,
        )
        self.ChangeSingleOrder = channel.unary_unary(
            '/SubmitOrderService/ChangeSingleOrder',
            request_serializer=order__pb2.ChangeSingleOrderRequest.SerializeToString,
            response_deserializer=order__pb2.ChangeSingleOrderResponse.FromString,
            _registered_method=True,
        )
        self.CancelSingleOrder = channel.unary_unary(
            '/SubmitOrderService/CancelSingleOrder',
            request_serializer=order__pb2.CancelSingleOrderRequest.SerializeToString,
            response_deserializer=order__pb2.CancelSingleOrderResponse.FromString,
            _registered_method=True,
        )
        self.SubmitSeedData = channel.unary_unary(
            '/SubmitOrderService/SubmitSeedData',
            request_serializer=order__pb2.SubmitSeedDataRequest.SerializeToString,
            response_deserializer=order__pb2.SubmitSeedDataResponse.FromString,
            _registered_method=True,
        )
        self.GetUserAccounts = channel.unary_unary(
            '/SubmitOrderService/GetUserAccounts',
            request_serializer=order__pb2.UserAccountsRequest.SerializeToString,
            response_deserializer=order__pb2.UserAccountsResponse.FromString,
            _registered_method=True,
        )
        self.SubmitBasketOrder = channel.unary_unary(
            '/SubmitOrderService/SubmitBasketOrder',
            request_serializer=order__pb2.BasketOrderRequest.SerializeToString,
            response_deserializer=order__pb2.BasketOrderResponse.FromString,
            _registered_method=True,
        )
        self.SubscribeOrderInfo = channel.unary_stream(
            '/SubmitOrderService/SubscribeOrderInfo',
            request_serializer=order__pb2.SubscribeOrderInfoRequest.SerializeToString,
            response_deserializer=order__pb2.SubscribeOrderInfoResponse.FromString,
            _registered_method=True,
        )
        self.SubmitAllocationOrder = channel.unary_unary(
            '/SubmitOrderService/SubmitAllocationOrder',
            request_serializer=order__pb2.SubmitAllocationOrderRequest.SerializeToString,
            response_deserializer=order__pb2.SubmitAllocationOrderResponse.FromString,
            _registered_method=True,
        )
        self.SubmitTradeReport = channel.unary_unary(
            '/SubmitOrderService/SubmitTradeReport',
            request_serializer=order__pb2.SubmitTradeReportRequest.SerializeToString,
            response_deserializer=order__pb2.SubmitTradeReportResponse.FromString,
            _registered_method=True,
        )
        self.SubscribeOrderInfoJson = channel.unary_stream(
            '/SubmitOrderService/SubscribeOrderInfoJson',
            request_serializer=order__pb2.SubscribeOrderInfoJsonRequest.SerializeToString,
            response_deserializer=order__pb2.SubscribeOrderInfoJsonResponse.FromString,
            _registered_method=True,
        )
        self.GetOrderDetailByOrderId = channel.unary_unary(
            '/SubmitOrderService/GetOrderDetailByOrderId',
            request_serializer=order__pb2.OrderDetailByOrderIdRequest.SerializeToString,
            response_deserializer=order__pb2.OrderDetailByOrderIdResponse.FromString,
            _registered_method=True,
        )
        self.GetOrderDetailByDateRange = channel.unary_stream(
            '/SubmitOrderService/GetOrderDetailByDateRange',
            request_serializer=order__pb2.OrderDetailByDateRangeRequest.SerializeToString,
            response_deserializer=order__pb2.OrderDetailByDateRangeResponse.FromString,
            _registered_method=True,
        )
        self.GetOrderDetailByOrderTag = channel.unary_unary(
            '/SubmitOrderService/GetOrderDetailByOrderTag',
            request_serializer=order__pb2.OrderDetailByOrderTagRequest.SerializeToString,
            response_deserializer=order__pb2.OrderDetailByOrderTagResponse.FromString,
            _registered_method=True,
        )


class SubmitOrderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitSingleOrder(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitBookTrade(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitPairOrder(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangePairOrder(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelPairOrder(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeSingleOrder(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelSingleOrder(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitSeedData(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserAccounts(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitBasketOrder(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeOrderInfo(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitAllocationOrder(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTradeReport(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeOrderInfoJson(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderDetailByOrderId(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderDetailByDateRange(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderDetailByOrderTag(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SubmitOrderServiceServicer_to_server(servicer, server):  # noqa: N802
    rpc_method_handlers = {
        'SubmitSingleOrder': grpc.unary_unary_rpc_method_handler(
            servicer.SubmitSingleOrder,
            request_deserializer=order__pb2.SubmitSingleOrderRequest.FromString,
            response_serializer=order__pb2.SubmitSingleOrderResponse.SerializeToString,
        ),
        'SubmitBookTrade': grpc.unary_unary_rpc_method_handler(
            servicer.SubmitBookTrade,
            request_deserializer=order__pb2.SubmitBookTradeRequest.FromString,
            response_serializer=order__pb2.SubmitBookTradeResponse.SerializeToString,
        ),
        'SubmitPairOrder': grpc.unary_unary_rpc_method_handler(
            servicer.SubmitPairOrder,
            request_deserializer=order__pb2.SubmitPairOrderRequest.FromString,
            response_serializer=order__pb2.SubmitPairOrderResponse.SerializeToString,
        ),
        'ChangePairOrder': grpc.unary_unary_rpc_method_handler(
            servicer.ChangePairOrder,
            request_deserializer=order__pb2.ChangePairOrderRequest.FromString,
            response_serializer=order__pb2.ChangePairOrderResponse.SerializeToString,
        ),
        'CancelPairOrder': grpc.unary_unary_rpc_method_handler(
            servicer.CancelPairOrder,
            request_deserializer=order__pb2.CancelPairOrderRequest.FromString,
            response_serializer=order__pb2.CancelPairOrderResponse.SerializeToString,
        ),
        'ChangeSingleOrder': grpc.unary_unary_rpc_method_handler(
            servicer.ChangeSingleOrder,
            request_deserializer=order__pb2.ChangeSingleOrderRequest.FromString,
            response_serializer=order__pb2.ChangeSingleOrderResponse.SerializeToString,
        ),
        'CancelSingleOrder': grpc.unary_unary_rpc_method_handler(
            servicer.CancelSingleOrder,
            request_deserializer=order__pb2.CancelSingleOrderRequest.FromString,
            response_serializer=order__pb2.CancelSingleOrderResponse.SerializeToString,
        ),
        'SubmitSeedData': grpc.unary_unary_rpc_method_handler(
            servicer.SubmitSeedData,
            request_deserializer=order__pb2.SubmitSeedDataRequest.FromString,
            response_serializer=order__pb2.SubmitSeedDataResponse.SerializeToString,
        ),
        'GetUserAccounts': grpc.unary_unary_rpc_method_handler(
            servicer.GetUserAccounts,
            request_deserializer=order__pb2.UserAccountsRequest.FromString,
            response_serializer=order__pb2.UserAccountsResponse.SerializeToString,
        ),
        'SubmitBasketOrder': grpc.unary_unary_rpc_method_handler(
            servicer.SubmitBasketOrder,
            request_deserializer=order__pb2.BasketOrderRequest.FromString,
            response_serializer=order__pb2.BasketOrderResponse.SerializeToString,
        ),
        'SubscribeOrderInfo': grpc.unary_stream_rpc_method_handler(
            servicer.SubscribeOrderInfo,
            request_deserializer=order__pb2.SubscribeOrderInfoRequest.FromString,
            response_serializer=order__pb2.SubscribeOrderInfoResponse.SerializeToString,
        ),
        'SubmitAllocationOrder': grpc.unary_unary_rpc_method_handler(
            servicer.SubmitAllocationOrder,
            request_deserializer=order__pb2.SubmitAllocationOrderRequest.FromString,
            response_serializer=order__pb2.SubmitAllocationOrderResponse.SerializeToString,
        ),
        'SubmitTradeReport': grpc.unary_unary_rpc_method_handler(
            servicer.SubmitTradeReport,
            request_deserializer=order__pb2.SubmitTradeReportRequest.FromString,
            response_serializer=order__pb2.SubmitTradeReportResponse.SerializeToString,
        ),
        'SubscribeOrderInfoJson': grpc.unary_stream_rpc_method_handler(
            servicer.SubscribeOrderInfoJson,
            request_deserializer=order__pb2.SubscribeOrderInfoJsonRequest.FromString,
            response_serializer=order__pb2.SubscribeOrderInfoJsonResponse.SerializeToString,
        ),
        'GetOrderDetailByOrderId': grpc.unary_unary_rpc_method_handler(
            servicer.GetOrderDetailByOrderId,
            request_deserializer=order__pb2.OrderDetailByOrderIdRequest.FromString,
            response_serializer=order__pb2.OrderDetailByOrderIdResponse.SerializeToString,
        ),
        'GetOrderDetailByDateRange': grpc.unary_stream_rpc_method_handler(
            servicer.GetOrderDetailByDateRange,
            request_deserializer=order__pb2.OrderDetailByDateRangeRequest.FromString,
            response_serializer=order__pb2.OrderDetailByDateRangeResponse.SerializeToString,
        ),
        'GetOrderDetailByOrderTag': grpc.unary_unary_rpc_method_handler(
            servicer.GetOrderDetailByOrderTag,
            request_deserializer=order__pb2.OrderDetailByOrderTagRequest.FromString,
            response_serializer=order__pb2.OrderDetailByOrderTagResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'SubmitOrderService', rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SubmitOrderService', rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class SubmitOrderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitSingleOrder(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SubmitOrderService/SubmitSingleOrder',
            order__pb2.SubmitSingleOrderRequest.SerializeToString,
            order__pb2.SubmitSingleOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SubmitBookTrade(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SubmitOrderService/SubmitBookTrade',
            order__pb2.SubmitBookTradeRequest.SerializeToString,
            order__pb2.SubmitBookTradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SubmitPairOrder(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SubmitOrderService/SubmitPairOrder',
            order__pb2.SubmitPairOrderRequest.SerializeToString,
            order__pb2.SubmitPairOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ChangePairOrder(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SubmitOrderService/ChangePairOrder',
            order__pb2.ChangePairOrderRequest.SerializeToString,
            order__pb2.ChangePairOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CancelPairOrder(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SubmitOrderService/CancelPairOrder',
            order__pb2.CancelPairOrderRequest.SerializeToString,
            order__pb2.CancelPairOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ChangeSingleOrder(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SubmitOrderService/ChangeSingleOrder',
            order__pb2.ChangeSingleOrderRequest.SerializeToString,
            order__pb2.ChangeSingleOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CancelSingleOrder(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SubmitOrderService/CancelSingleOrder',
            order__pb2.CancelSingleOrderRequest.SerializeToString,
            order__pb2.CancelSingleOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SubmitSeedData(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SubmitOrderService/SubmitSeedData',
            order__pb2.SubmitSeedDataRequest.SerializeToString,
            order__pb2.SubmitSeedDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetUserAccounts(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SubmitOrderService/GetUserAccounts',
            order__pb2.UserAccountsRequest.SerializeToString,
            order__pb2.UserAccountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SubmitBasketOrder(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SubmitOrderService/SubmitBasketOrder',
            order__pb2.BasketOrderRequest.SerializeToString,
            order__pb2.BasketOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SubscribeOrderInfo(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/SubmitOrderService/SubscribeOrderInfo',
            order__pb2.SubscribeOrderInfoRequest.SerializeToString,
            order__pb2.SubscribeOrderInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SubmitAllocationOrder(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SubmitOrderService/SubmitAllocationOrder',
            order__pb2.SubmitAllocationOrderRequest.SerializeToString,
            order__pb2.SubmitAllocationOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SubmitTradeReport(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SubmitOrderService/SubmitTradeReport',
            order__pb2.SubmitTradeReportRequest.SerializeToString,
            order__pb2.SubmitTradeReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SubscribeOrderInfoJson(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/SubmitOrderService/SubscribeOrderInfoJson',
            order__pb2.SubscribeOrderInfoJsonRequest.SerializeToString,
            order__pb2.SubscribeOrderInfoJsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetOrderDetailByOrderId(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SubmitOrderService/GetOrderDetailByOrderId',
            order__pb2.OrderDetailByOrderIdRequest.SerializeToString,
            order__pb2.OrderDetailByOrderIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetOrderDetailByDateRange(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/SubmitOrderService/GetOrderDetailByDateRange',
            order__pb2.OrderDetailByDateRangeRequest.SerializeToString,
            order__pb2.OrderDetailByDateRangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetOrderDetailByOrderTag(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SubmitOrderService/GetOrderDetailByOrderTag',
            order__pb2.OrderDetailByOrderTagRequest.SerializeToString,
            order__pb2.OrderDetailByOrderTagResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
