# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings  # noqa: F401

import grpc

import grpc_generated.utilities_pb2 as utilities__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in utilities_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UtilityServicesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTodaysBalances = channel.unary_unary(
            '/UtilityServices/GetTodaysBalances',
            request_serializer=utilities__pb2.TodaysBalancesRequest.SerializeToString,
            response_deserializer=utilities__pb2.TodaysBalancesResponse.FromString,
            _registered_method=True,
        )
        self.GetTodaysActivity = channel.unary_unary(
            '/UtilityServices/GetTodaysActivity',
            request_serializer=utilities__pb2.TodaysActivityRequest.SerializeToString,
            response_deserializer=utilities__pb2.TodaysActivityResponse.FromString,
            _registered_method=True,
        )
        self.GetTodaysBrokenDownPositions = channel.unary_unary(
            '/UtilityServices/GetTodaysBrokenDownPositions',
            request_serializer=utilities__pb2.TodaysBrokenDownPositionsRequest.SerializeToString,
            response_deserializer=utilities__pb2.TodaysBrokenDownPositionsResponse.FromString,
            _registered_method=True,
        )
        self.GetTodaysNetPositions = channel.unary_unary(
            '/UtilityServices/GetTodaysNetPositions',
            request_serializer=utilities__pb2.TodaysNetPositionsRequest.SerializeToString,
            response_deserializer=utilities__pb2.TodaysNetPositionsResponse.FromString,
            _registered_method=True,
        )
        self.SubscribeTodaysNetPositions = channel.unary_stream(
            '/UtilityServices/SubscribeTodaysNetPositions',
            request_serializer=utilities__pb2.SubscribeNetPositionsRequest.SerializeToString,
            response_deserializer=utilities__pb2.SubscribeNetPositionsResponse.FromString,
            _registered_method=True,
        )
        self.UnSubscribeTodaysNetPositions = channel.unary_unary(
            '/UtilityServices/UnSubscribeTodaysNetPositions',
            request_serializer=utilities__pb2.UnSubscribeNetPositionsRequest.SerializeToString,
            response_deserializer=utilities__pb2.UnSubscribeNetPositionsResponse.FromString,
            _registered_method=True,
        )
        self.Connect = channel.unary_unary(
            '/UtilityServices/Connect',
            request_serializer=utilities__pb2.ConnectRequest.SerializeToString,
            response_deserializer=utilities__pb2.ConnectResponse.FromString,
            _registered_method=True,
        )
        self.SubscribeHeartBeat = channel.unary_stream(
            '/UtilityServices/SubscribeHeartBeat',
            request_serializer=utilities__pb2.SubscribeHeartBeatRequest.SerializeToString,
            response_deserializer=utilities__pb2.SubscribeHeartBeatResponse.FromString,
            _registered_method=True,
        )
        self.Disconnect = channel.unary_unary(
            '/UtilityServices/Disconnect',
            request_serializer=utilities__pb2.DisconnectRequest.SerializeToString,
            response_deserializer=utilities__pb2.DisconnectResponse.FromString,
            _registered_method=True,
        )
        self.StartLoginSrp = channel.unary_unary(
            '/UtilityServices/StartLoginSrp',
            request_serializer=utilities__pb2.StartLoginSrpRequest.SerializeToString,
            response_deserializer=utilities__pb2.StartLoginSrpResponse.FromString,
            _registered_method=True,
        )
        self.CompleteLoginSrp = channel.unary_unary(
            '/UtilityServices/CompleteLoginSrp',
            request_serializer=utilities__pb2.CompleteLoginSrpRequest.SerializeToString,
            response_deserializer=utilities__pb2.CompleteLoginSrpResponse.FromString,
            _registered_method=True,
        )
        self.ChangePasswordSRP = channel.unary_unary(
            '/UtilityServices/ChangePasswordSRP',
            request_serializer=utilities__pb2.ChangePasswordSRPRequest.SerializeToString,
            response_deserializer=utilities__pb2.ChangePasswordSRPResponse.FromString,
            _registered_method=True,
        )
        self.GetStrategyList = channel.unary_unary(
            '/UtilityServices/GetStrategyList',
            request_serializer=utilities__pb2.StrategyListRequest.SerializeToString,
            response_deserializer=utilities__pb2.StrategyListResponse.FromString,
            _registered_method=True,
        )
        self.GetFirmName = channel.unary_unary(
            '/UtilityServices/GetFirmName',
            request_serializer=utilities__pb2.GetFirmNameRequest.SerializeToString,
            response_deserializer=utilities__pb2.GetFirmNameResponse.FromString,
            _registered_method=True,
        )
        self.UserExists = channel.unary_unary(
            '/UtilityServices/UserExists',
            request_serializer=utilities__pb2.UserExistsRequest.SerializeToString,
            response_deserializer=utilities__pb2.UserExistsResponse.FromString,
            _registered_method=True,
        )
        self.GetStrategyData = channel.unary_unary(
            '/UtilityServices/GetStrategyData',
            request_serializer=utilities__pb2.GetStrategyDataRequest.SerializeToString,
            response_deserializer=utilities__pb2.GetStrategyDataResponse.FromString,
            _registered_method=True,
        )
        self.CreateStrategy = channel.unary_unary(
            '/UtilityServices/CreateStrategy',
            request_serializer=utilities__pb2.CreateStrategyRequest.SerializeToString,
            response_deserializer=utilities__pb2.CreateStrategyResponse.FromString,
            _registered_method=True,
        )
        self.UpdateStrategy = channel.unary_unary(
            '/UtilityServices/UpdateStrategy',
            request_serializer=utilities__pb2.UpdateStrategyRequest.SerializeToString,
            response_deserializer=utilities__pb2.UpdateStrategyResponse.FromString,
            _registered_method=True,
        )
        self.GetTodaysActivityJson = channel.unary_unary(
            '/UtilityServices/GetTodaysActivityJson',
            request_serializer=utilities__pb2.TodaysActivityJsonRequest.SerializeToString,
            response_deserializer=utilities__pb2.TodaysActivityJsonResponse.FromString,
            _registered_method=True,
        )
        self.GetUserRoutes = channel.unary_unary(
            '/UtilityServices/GetUserRoutes',
            request_serializer=utilities__pb2.GetUserRoutesRequest.SerializeToString,
            response_deserializer=utilities__pb2.GetUserRoutesResponse.FromString,
            _registered_method=True,
        )
        self.GetUserRouteProps = channel.unary_unary(
            '/UtilityServices/GetUserRouteProps',
            request_serializer=utilities__pb2.GetUserRoutePropsRequest.SerializeToString,
            response_deserializer=utilities__pb2.GetUserRoutePropsResponse.FromString,
            _registered_method=True,
        )


class UtilityServicesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTodaysBalances(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTodaysActivity(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTodaysBrokenDownPositions(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTodaysNetPositions(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeTodaysNetPositions(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnSubscribeTodaysNetPositions(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connect(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeHeartBeat(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disconnect(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartLoginSrp(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteLoginSrp(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangePasswordSRP(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStrategyList(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFirmName(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserExists(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStrategyData(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateStrategy(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStrategy(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTodaysActivityJson(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserRoutes(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserRouteProps(self, request, context):  # noqa: N802
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UtilityServicesServicer_to_server(servicer, server):  # noqa: N802
    rpc_method_handlers = {
        'GetTodaysBalances': grpc.unary_unary_rpc_method_handler(
            servicer.GetTodaysBalances,
            request_deserializer=utilities__pb2.TodaysBalancesRequest.FromString,
            response_serializer=utilities__pb2.TodaysBalancesResponse.SerializeToString,
        ),
        'GetTodaysActivity': grpc.unary_unary_rpc_method_handler(
            servicer.GetTodaysActivity,
            request_deserializer=utilities__pb2.TodaysActivityRequest.FromString,
            response_serializer=utilities__pb2.TodaysActivityResponse.SerializeToString,
        ),
        'GetTodaysBrokenDownPositions': grpc.unary_unary_rpc_method_handler(
            servicer.GetTodaysBrokenDownPositions,
            request_deserializer=utilities__pb2.TodaysBrokenDownPositionsRequest.FromString,
            response_serializer=utilities__pb2.TodaysBrokenDownPositionsResponse.SerializeToString,
        ),
        'GetTodaysNetPositions': grpc.unary_unary_rpc_method_handler(
            servicer.GetTodaysNetPositions,
            request_deserializer=utilities__pb2.TodaysNetPositionsRequest.FromString,
            response_serializer=utilities__pb2.TodaysNetPositionsResponse.SerializeToString,
        ),
        'SubscribeTodaysNetPositions': grpc.unary_stream_rpc_method_handler(
            servicer.SubscribeTodaysNetPositions,
            request_deserializer=utilities__pb2.SubscribeNetPositionsRequest.FromString,
            response_serializer=utilities__pb2.SubscribeNetPositionsResponse.SerializeToString,
        ),
        'UnSubscribeTodaysNetPositions': grpc.unary_unary_rpc_method_handler(
            servicer.UnSubscribeTodaysNetPositions,
            request_deserializer=utilities__pb2.UnSubscribeNetPositionsRequest.FromString,
            response_serializer=utilities__pb2.UnSubscribeNetPositionsResponse.SerializeToString,
        ),
        'Connect': grpc.unary_unary_rpc_method_handler(
            servicer.Connect,
            request_deserializer=utilities__pb2.ConnectRequest.FromString,
            response_serializer=utilities__pb2.ConnectResponse.SerializeToString,
        ),
        'SubscribeHeartBeat': grpc.unary_stream_rpc_method_handler(
            servicer.SubscribeHeartBeat,
            request_deserializer=utilities__pb2.SubscribeHeartBeatRequest.FromString,
            response_serializer=utilities__pb2.SubscribeHeartBeatResponse.SerializeToString,
        ),
        'Disconnect': grpc.unary_unary_rpc_method_handler(
            servicer.Disconnect,
            request_deserializer=utilities__pb2.DisconnectRequest.FromString,
            response_serializer=utilities__pb2.DisconnectResponse.SerializeToString,
        ),
        'StartLoginSrp': grpc.unary_unary_rpc_method_handler(
            servicer.StartLoginSrp,
            request_deserializer=utilities__pb2.StartLoginSrpRequest.FromString,
            response_serializer=utilities__pb2.StartLoginSrpResponse.SerializeToString,
        ),
        'CompleteLoginSrp': grpc.unary_unary_rpc_method_handler(
            servicer.CompleteLoginSrp,
            request_deserializer=utilities__pb2.CompleteLoginSrpRequest.FromString,
            response_serializer=utilities__pb2.CompleteLoginSrpResponse.SerializeToString,
        ),
        'ChangePasswordSRP': grpc.unary_unary_rpc_method_handler(
            servicer.ChangePasswordSRP,
            request_deserializer=utilities__pb2.ChangePasswordSRPRequest.FromString,
            response_serializer=utilities__pb2.ChangePasswordSRPResponse.SerializeToString,
        ),
        'GetStrategyList': grpc.unary_unary_rpc_method_handler(
            servicer.GetStrategyList,
            request_deserializer=utilities__pb2.StrategyListRequest.FromString,
            response_serializer=utilities__pb2.StrategyListResponse.SerializeToString,
        ),
        'GetFirmName': grpc.unary_unary_rpc_method_handler(
            servicer.GetFirmName,
            request_deserializer=utilities__pb2.GetFirmNameRequest.FromString,
            response_serializer=utilities__pb2.GetFirmNameResponse.SerializeToString,
        ),
        'UserExists': grpc.unary_unary_rpc_method_handler(
            servicer.UserExists,
            request_deserializer=utilities__pb2.UserExistsRequest.FromString,
            response_serializer=utilities__pb2.UserExistsResponse.SerializeToString,
        ),
        'GetStrategyData': grpc.unary_unary_rpc_method_handler(
            servicer.GetStrategyData,
            request_deserializer=utilities__pb2.GetStrategyDataRequest.FromString,
            response_serializer=utilities__pb2.GetStrategyDataResponse.SerializeToString,
        ),
        'CreateStrategy': grpc.unary_unary_rpc_method_handler(
            servicer.CreateStrategy,
            request_deserializer=utilities__pb2.CreateStrategyRequest.FromString,
            response_serializer=utilities__pb2.CreateStrategyResponse.SerializeToString,
        ),
        'UpdateStrategy': grpc.unary_unary_rpc_method_handler(
            servicer.UpdateStrategy,
            request_deserializer=utilities__pb2.UpdateStrategyRequest.FromString,
            response_serializer=utilities__pb2.UpdateStrategyResponse.SerializeToString,
        ),
        'GetTodaysActivityJson': grpc.unary_unary_rpc_method_handler(
            servicer.GetTodaysActivityJson,
            request_deserializer=utilities__pb2.TodaysActivityJsonRequest.FromString,
            response_serializer=utilities__pb2.TodaysActivityJsonResponse.SerializeToString,
        ),
        'GetUserRoutes': grpc.unary_unary_rpc_method_handler(
            servicer.GetUserRoutes,
            request_deserializer=utilities__pb2.GetUserRoutesRequest.FromString,
            response_serializer=utilities__pb2.GetUserRoutesResponse.SerializeToString,
        ),
        'GetUserRouteProps': grpc.unary_unary_rpc_method_handler(
            servicer.GetUserRouteProps,
            request_deserializer=utilities__pb2.GetUserRoutePropsRequest.FromString,
            response_serializer=utilities__pb2.GetUserRoutePropsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler('UtilityServices', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('UtilityServices', rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class UtilityServices(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTodaysBalances(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UtilityServices/GetTodaysBalances',
            utilities__pb2.TodaysBalancesRequest.SerializeToString,
            utilities__pb2.TodaysBalancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTodaysActivity(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UtilityServices/GetTodaysActivity',
            utilities__pb2.TodaysActivityRequest.SerializeToString,
            utilities__pb2.TodaysActivityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTodaysBrokenDownPositions(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UtilityServices/GetTodaysBrokenDownPositions',
            utilities__pb2.TodaysBrokenDownPositionsRequest.SerializeToString,
            utilities__pb2.TodaysBrokenDownPositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTodaysNetPositions(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UtilityServices/GetTodaysNetPositions',
            utilities__pb2.TodaysNetPositionsRequest.SerializeToString,
            utilities__pb2.TodaysNetPositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SubscribeTodaysNetPositions(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/UtilityServices/SubscribeTodaysNetPositions',
            utilities__pb2.SubscribeNetPositionsRequest.SerializeToString,
            utilities__pb2.SubscribeNetPositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UnSubscribeTodaysNetPositions(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UtilityServices/UnSubscribeTodaysNetPositions',
            utilities__pb2.UnSubscribeNetPositionsRequest.SerializeToString,
            utilities__pb2.UnSubscribeNetPositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Connect(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UtilityServices/Connect',
            utilities__pb2.ConnectRequest.SerializeToString,
            utilities__pb2.ConnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SubscribeHeartBeat(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/UtilityServices/SubscribeHeartBeat',
            utilities__pb2.SubscribeHeartBeatRequest.SerializeToString,
            utilities__pb2.SubscribeHeartBeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Disconnect(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UtilityServices/Disconnect',
            utilities__pb2.DisconnectRequest.SerializeToString,
            utilities__pb2.DisconnectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StartLoginSrp(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UtilityServices/StartLoginSrp',
            utilities__pb2.StartLoginSrpRequest.SerializeToString,
            utilities__pb2.StartLoginSrpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CompleteLoginSrp(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UtilityServices/CompleteLoginSrp',
            utilities__pb2.CompleteLoginSrpRequest.SerializeToString,
            utilities__pb2.CompleteLoginSrpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ChangePasswordSRP(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UtilityServices/ChangePasswordSRP',
            utilities__pb2.ChangePasswordSRPRequest.SerializeToString,
            utilities__pb2.ChangePasswordSRPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetStrategyList(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UtilityServices/GetStrategyList',
            utilities__pb2.StrategyListRequest.SerializeToString,
            utilities__pb2.StrategyListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetFirmName(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UtilityServices/GetFirmName',
            utilities__pb2.GetFirmNameRequest.SerializeToString,
            utilities__pb2.GetFirmNameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UserExists(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UtilityServices/UserExists',
            utilities__pb2.UserExistsRequest.SerializeToString,
            utilities__pb2.UserExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetStrategyData(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UtilityServices/GetStrategyData',
            utilities__pb2.GetStrategyDataRequest.SerializeToString,
            utilities__pb2.GetStrategyDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateStrategy(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UtilityServices/CreateStrategy',
            utilities__pb2.CreateStrategyRequest.SerializeToString,
            utilities__pb2.CreateStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateStrategy(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UtilityServices/UpdateStrategy',
            utilities__pb2.UpdateStrategyRequest.SerializeToString,
            utilities__pb2.UpdateStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTodaysActivityJson(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UtilityServices/GetTodaysActivityJson',
            utilities__pb2.TodaysActivityJsonRequest.SerializeToString,
            utilities__pb2.TodaysActivityJsonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetUserRoutes(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UtilityServices/GetUserRoutes',
            utilities__pb2.GetUserRoutesRequest.SerializeToString,
            utilities__pb2.GetUserRoutesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetUserRouteProps(  # noqa: N802
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UtilityServices/GetUserRouteProps',
            utilities__pb2.GetUserRoutePropsRequest.SerializeToString,
            utilities__pb2.GetUserRoutePropsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
